### ISSUE TITLE
Possible double-free?

### ISSUE THREAD

**Issue by baptistapedro** [keystone-enclave/linux-keystone-driver#18]
```
vaddr_t get_free_page(struct list_head* pg_list)
{

	<---------------- (a) //  null checks should be needed for pg_list


  struct free_page* page;
  vaddr_t addr;

  if(list_empty(pg_list))
    return 0;

  page = list_first_entry(pg_list, struct free_page, freelist);  <--------- (b) //    this probably can return an unexpected/undefined value
  addr = page->vaddr;
  list_del(&page->freelist);
  kfree(page);                  <--------- //  because of (a), (b), page may never be allocated and 
                                                              therefore happen a some sort of 	double free?

  return addr;
}
```

**Comment by baptistapedro** [comment]
the lack of checks on some attrs is definitely a concern on the behaviour of the driver.

list_empty(pg_list))  - this only returns 0 if the whole struct is empty/unint.
A null check above it may be needed?

if list_frist_entry() fails and page returns an unexpected value or isn't even initialized.
&page->freelist may deref to somewhere else?

**Comment by dkohlbre** [comment]
list_first_entry() doesn't return a failure value, and assumes the list is non-empty. (This is part of the standard linked lists for kernel structures, not keystone driver code).

The only items added to the list are allocated objects, so there will not be 'unusual' returns from first_entry().

pg_list is never null as this is only called internally.

Overall, this is a set of internal helper functions that are not accessible by other parts of the driver, and can make strong assumptions about their operating state safely.
