### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by baptistapedro** [keystone-enclave/linux-keystone-driver#19]
```

int keystone_create_enclave(struct file *filep, unsigned long arg)
{
  /* create parameters */
  struct keystone_ioctl_create_enclave *enclp = (struct keystone_ioctl_create_enclave *) arg;

  struct enclave *enclave;
  enclave = create_enclave(enclp->min_pages);      <---------- // there's no boundary check for enclp->min_pages value on create_enclave().

  if (enclave == NULL) {
    return -ENOMEM;
  }

  /* allocate UID */
  enclp->eid = enclave_idr_alloc(enclave);

  filep->private_data = (void *) enclp->eid;

  return 0;
}




struct enclave* create_enclave(unsigned long min_pages)
{
  struct enclave* enclave;

  enclave = kmalloc(sizeof(struct enclave), GFP_KERNEL);
  if (!enclave){
    keystone_err("failed to allocate enclave struct\n");
    goto error_no_free;
  }

  enclave->utm = NULL;
  enclave->close_on_pexit = 1;

  enclave->epm = kmalloc(sizeof(struct epm), GFP_KERNEL);
  if (!enclave->epm)
  {
    keystone_err("failed to allocate epm\n");
    goto error_destroy_enclave;
  }

  if(epm_init(enclave->epm, min_pages)) {
    keystone_err("failed to initialize epm\n");
    goto error_destroy_enclave;
  }
  return enclave;

 error_destroy_enclave:
  destroy_enclave(enclave);
 error_no_free:
  return NULL;
}

````

**Comment by baptistapedro** [comment]
enclp->min_pages can be any huge number... possibly adding a filter on it may protect further issues?

**Comment by dkohlbre** [comment]
I don't see any dangerous usage of min_pages that can result in overflow/underflow issues. A sanity limit is not a bad idea, but there are no possible overflows that I can see.
Did you have a specific case in mind?

**Comment by baptistapedro** [comment]
Yeah a sanity check is indeed all it needs, I guess.

I don't have a specific case in mind but we must assume that most of the devices running the driver is 64bit, considering that detail if min_pages is 0xffffffff wouldn't make any difference further on?

**Comment by dkohlbre** [comment]
There are no math operations done on min_pages, so its not going to have issues in this case. I'll also note that for very large values the attempt to allocate that many pages will almost certainly fail anyway.

I'll add a sanity check but otherwise there is no issue here.
