### ISSUE TITLE
Off-by-One

### ISSUE THREAD

**Issue by baptistapedro** [keystone-enclave/linux-keystone-driver#20]
```
long keystone_ioctl(struct file *filep, unsigned int cmd, unsigned long arg)
{
  long ret;
  char data[256];
  size_t ioc_size;

  if (!arg)
    return -EINVAL;

  ioc_size = _IOC_SIZE(cmd);
  ioc_size = ioc_size > sizeof(data) ? sizeof(data) : ioc_size;        <-------- // dont let ioc_size be == sizeof(data)

  if (copy_from_user(data,(void __user *) arg, ioc_size))    <------------ // (a)
    return -EFAULT;
  [...]



// (a) - as we're dealing with possible strings a null termination would be needed if __user *arg == sizeof(data)
// specially coming from the userspace; off-by-one may occur

```

**Comment by dkohlbre** [comment]
There is an issue here, in that the correct behavior if IOC_SIZE is too large is to fail, or to allocate a properly sized buffer. A static buffer isn't a great solution for us.

I'm not sure what you mean by an off-by-one error. We don't know (nor is the ioctl part of the driver interface responsible for) the type of the data. None of the data we pass is strings, and if it were it would not be an off-by-one error to truncate it. Is there something further about this I'm missing?

**Comment by baptistapedro** [comment]
if we were dealing with strings we probably could have an overflow by 1 byte.

If you use copy_from_user and getting a string as input and you're copying exactly the same length as your buffer size, you should null terminate it.
If the data passed isn't strings, then it's ok

**Comment by dkohlbre** [comment]
When copying unknown data from the user we trust the size they pass us. C-string semantics aren't relevant to the copy, its the user-space's job to ensure the size is correct.
