### ISSUE TITLE
double-free on *epm - UAF ?

### ISSUE THREAD

**Issue by baptistapedro** [keystone-enclave/linux-keystone-driver#21]
```
int epm_destroy(struct epm* epm) {

  /* Clean anything in the free list */
  epm_clean_free_list(epm);         <---------------- free every single  epm struct on the list

  if(!epm->ptr || !epm->size)
    return 0;                                <------------ if ->ptr and ->size is definitely unint we will break/return here.

  /* free the EPM hold by the enclave */
  if (epm->is_cma) {
    dma_free_coherent(keystone_dev.this_device,
        epm->size,
        (void*) epm->ptr,
        epm->pa);
  } else {
    free_pages(epm->ptr, epm->order);
  }

  return 0;
}



int destroy_enclave(struct enclave* enclave)
{
  struct epm* epm;
  struct utm* utm;
  if (enclave == NULL)
    return -ENOSYS;

  epm = enclave->epm;
  utm = enclave->utm;

  if (epm)
  {
    epm_destroy(epm);             <----------------- at this point we have freed all epm properties from the list...
    kfree(epm);        <------------ we're freeing them again....
  } 
  if (utm)
  {
    utm_destroy(utm);
    kfree(utm);
  }
  kfree(enclave);
  return 0;
}

```

**Comment by dkohlbre** [comment]
I'm slightly confused on this one. Can you provide a bit more info?

`epm_destroy` will free/remove all entities inside the epm, it will not (skimming the code again) free the actual allocated epm control object that was created in `create_enclave`:
` enclave->epm = kmalloc(sizeof(struct epm), GFP_KERNEL);`

Is there something I'm missing about how `epm_destroy` works?

There does appear to be a safety issue in that 
```
  if (epm)
  {
    epm_destroy(epm);  
    kfree(epm); 
  } 
```
Doesn't set epm to `0`.

**Comment by baptistapedro** [comment]
I probably may have misunderstood this but:

epm_destroy - destroy all entities on epm
kfree(epm) - free the whole epm struct

Both methods are freeing an object previously created on create_enclave right? One handles the epm's entities and another frees the object itself.
Do we really need both methods, because the 2nd  `if block` on epm_destroy that may never run.

**Comment by dkohlbre** [comment]
They are logically distinct operations, and the pattern of allocation/destruction matches between the two (epm_ methods deal with internals, the external control structure is managed by the enclave struct lifecycle). The `if` block in `epm_destroy` is unrelated to the `kfree(epm)` and does not interact with the same memory.

I don't think there is any UAF/double free here, though I will make sure the epm gets set to 0 after freeing.

In general when filing (especially security) issues, it is helpful if the bug title is accurate to the perceived issue. IE: in this (and several of the other issues filed like issue #20 ) case I think it may have been better to file a single issue about general code quality and defensiveness with these as examples.
If you can, I'd appreciate you going through the other issues you've filed and making sure there is a specific identified instance of the issue that the bug title suggests. I'm happy to go through them at that point.

**Comment by dkohlbre** [comment]
I'm going to close this out. Please re-open if you believe its still a possible issue.
